/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as WatermarkRouteImport } from './app/watermark'
import { Route as TracerRouteImport } from './app/tracer'
import { Route as TermsRouteImport } from './app/terms'
import { Route as SitemapDotxmlRouteImport } from './app/sitemap[.]xml'
import { Route as ScrubRouteImport } from './app/scrub'
import { Route as RobotsDottxtRouteImport } from './app/robots[.]txt'
import { Route as ResizeRouteImport } from './app/resize'
import { Route as PrivacyRouteImport } from './app/privacy'
import { Route as PdfRouteImport } from './app/pdf'
import { Route as PaletteRouteImport } from './app/palette'
import { Route as ManifestDotwebmanifestRouteImport } from './app/manifest[.]webmanifest'
import { Route as LlmsDottxtRouteImport } from './app/llms[.]txt'
import { Route as GlassRouteImport } from './app/glass'
import { Route as FiltersRouteImport } from './app/filters'
import { Route as FaviconRouteImport } from './app/favicon'
import { Route as CropRouteImport } from './app/crop'
import { Route as ConvertRouteImport } from './app/convert'
import { Route as CompareRouteImport } from './app/compare'
import { Route as CliRouteImport } from './app/cli'
import { Route as IndexRouteImport } from './app/index'
import { Route as IngestSplatRouteImport } from './app/ingest/$'
import { Route as ApiWatermarkRouteImport } from './app/api/watermark'
import { Route as ApiScrubRouteImport } from './app/api/scrub'
import { Route as ApiFaviconRouteImport } from './app/api/favicon'
import { Route as ApiCompressRouteImport } from './app/api/compress'
import { Route as IngestStaticSplatRouteImport } from './app/ingest/static/$'

const WatermarkRoute = WatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const TracerRoute = TracerRouteImport.update({
  id: '/tracer',
  path: '/tracer',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrubRoute = ScrubRouteImport.update({
  id: '/scrub',
  path: '/scrub',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizeRoute = ResizeRouteImport.update({
  id: '/resize',
  path: '/resize',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PaletteRoute = PaletteRouteImport.update({
  id: '/palette',
  path: '/palette',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassRoute = GlassRouteImport.update({
  id: '/glass',
  path: '/glass',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltersRoute = FiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconRoute = FaviconRouteImport.update({
  id: '/favicon',
  path: '/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const CropRoute = CropRouteImport.update({
  id: '/crop',
  path: '/crop',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestSplatRoute = IngestSplatRouteImport.update({
  id: '/ingest/$',
  path: '/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatermarkRoute = ApiWatermarkRouteImport.update({
  id: '/api/watermark',
  path: '/api/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrubRoute = ApiScrubRouteImport.update({
  id: '/api/scrub',
  path: '/api/scrub',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaviconRoute = ApiFaviconRouteImport.update({
  id: '/api/favicon',
  path: '/api/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompressRoute = ApiCompressRouteImport.update({
  id: '/api/compress',
  path: '/api/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestStaticSplatRoute = IngestStaticSplatRouteImport.update({
  id: '/ingest/static/$',
  path: '/ingest/static/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/convert': typeof ConvertRoute
  '/crop': typeof CropRoute
  '/favicon': typeof FaviconRoute
  '/filters': typeof FiltersRoute
  '/glass': typeof GlassRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/palette': typeof PaletteRoute
  '/pdf': typeof PdfRoute
  '/privacy': typeof PrivacyRoute
  '/resize': typeof ResizeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scrub': typeof ScrubRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tracer': typeof TracerRoute
  '/watermark': typeof WatermarkRoute
  '/api/compress': typeof ApiCompressRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/scrub': typeof ApiScrubRoute
  '/api/watermark': typeof ApiWatermarkRoute
  '/ingest/$': typeof IngestSplatRoute
  '/ingest/static/$': typeof IngestStaticSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/convert': typeof ConvertRoute
  '/crop': typeof CropRoute
  '/favicon': typeof FaviconRoute
  '/filters': typeof FiltersRoute
  '/glass': typeof GlassRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/palette': typeof PaletteRoute
  '/pdf': typeof PdfRoute
  '/privacy': typeof PrivacyRoute
  '/resize': typeof ResizeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scrub': typeof ScrubRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tracer': typeof TracerRoute
  '/watermark': typeof WatermarkRoute
  '/api/compress': typeof ApiCompressRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/scrub': typeof ApiScrubRoute
  '/api/watermark': typeof ApiWatermarkRoute
  '/ingest/$': typeof IngestSplatRoute
  '/ingest/static/$': typeof IngestStaticSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/convert': typeof ConvertRoute
  '/crop': typeof CropRoute
  '/favicon': typeof FaviconRoute
  '/filters': typeof FiltersRoute
  '/glass': typeof GlassRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/palette': typeof PaletteRoute
  '/pdf': typeof PdfRoute
  '/privacy': typeof PrivacyRoute
  '/resize': typeof ResizeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scrub': typeof ScrubRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tracer': typeof TracerRoute
  '/watermark': typeof WatermarkRoute
  '/api/compress': typeof ApiCompressRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/scrub': typeof ApiScrubRoute
  '/api/watermark': typeof ApiWatermarkRoute
  '/ingest/$': typeof IngestSplatRoute
  '/ingest/static/$': typeof IngestStaticSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli'
    | '/compare'
    | '/convert'
    | '/crop'
    | '/favicon'
    | '/filters'
    | '/glass'
    | '/llms.txt'
    | '/manifest.webmanifest'
    | '/palette'
    | '/pdf'
    | '/privacy'
    | '/resize'
    | '/robots.txt'
    | '/scrub'
    | '/sitemap.xml'
    | '/terms'
    | '/tracer'
    | '/watermark'
    | '/api/compress'
    | '/api/favicon'
    | '/api/scrub'
    | '/api/watermark'
    | '/ingest/$'
    | '/ingest/static/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli'
    | '/compare'
    | '/convert'
    | '/crop'
    | '/favicon'
    | '/filters'
    | '/glass'
    | '/llms.txt'
    | '/manifest.webmanifest'
    | '/palette'
    | '/pdf'
    | '/privacy'
    | '/resize'
    | '/robots.txt'
    | '/scrub'
    | '/sitemap.xml'
    | '/terms'
    | '/tracer'
    | '/watermark'
    | '/api/compress'
    | '/api/favicon'
    | '/api/scrub'
    | '/api/watermark'
    | '/ingest/$'
    | '/ingest/static/$'
  id:
    | '__root__'
    | '/'
    | '/cli'
    | '/compare'
    | '/convert'
    | '/crop'
    | '/favicon'
    | '/filters'
    | '/glass'
    | '/llms.txt'
    | '/manifest.webmanifest'
    | '/palette'
    | '/pdf'
    | '/privacy'
    | '/resize'
    | '/robots.txt'
    | '/scrub'
    | '/sitemap.xml'
    | '/terms'
    | '/tracer'
    | '/watermark'
    | '/api/compress'
    | '/api/favicon'
    | '/api/scrub'
    | '/api/watermark'
    | '/ingest/$'
    | '/ingest/static/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliRoute: typeof CliRoute
  CompareRoute: typeof CompareRoute
  ConvertRoute: typeof ConvertRoute
  CropRoute: typeof CropRoute
  FaviconRoute: typeof FaviconRoute
  FiltersRoute: typeof FiltersRoute
  GlassRoute: typeof GlassRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  PaletteRoute: typeof PaletteRoute
  PdfRoute: typeof PdfRoute
  PrivacyRoute: typeof PrivacyRoute
  ResizeRoute: typeof ResizeRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ScrubRoute: typeof ScrubRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TracerRoute: typeof TracerRoute
  WatermarkRoute: typeof WatermarkRoute
  ApiCompressRoute: typeof ApiCompressRoute
  ApiFaviconRoute: typeof ApiFaviconRoute
  ApiScrubRoute: typeof ApiScrubRoute
  ApiWatermarkRoute: typeof ApiWatermarkRoute
  IngestSplatRoute: typeof IngestSplatRoute
  IngestStaticSplatRoute: typeof IngestStaticSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watermark': {
      id: '/watermark'
      path: '/watermark'
      fullPath: '/watermark'
      preLoaderRoute: typeof WatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracer': {
      id: '/tracer'
      path: '/tracer'
      fullPath: '/tracer'
      preLoaderRoute: typeof TracerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrub': {
      id: '/scrub'
      path: '/scrub'
      fullPath: '/scrub'
      preLoaderRoute: typeof ScrubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resize': {
      id: '/resize'
      path: '/resize'
      fullPath: '/resize'
      preLoaderRoute: typeof ResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palette': {
      id: '/palette'
      path: '/palette'
      fullPath: '/palette'
      preLoaderRoute: typeof PaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glass': {
      id: '/glass'
      path: '/glass'
      fullPath: '/glass'
      preLoaderRoute: typeof GlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filters': {
      id: '/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof FiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon': {
      id: '/favicon'
      path: '/favicon'
      fullPath: '/favicon'
      preLoaderRoute: typeof FaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop': {
      id: '/crop'
      path: '/crop'
      fullPath: '/crop'
      preLoaderRoute: typeof CropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest/$': {
      id: '/ingest/$'
      path: '/ingest/$'
      fullPath: '/ingest/$'
      preLoaderRoute: typeof IngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watermark': {
      id: '/api/watermark'
      path: '/api/watermark'
      fullPath: '/api/watermark'
      preLoaderRoute: typeof ApiWatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrub': {
      id: '/api/scrub'
      path: '/api/scrub'
      fullPath: '/api/scrub'
      preLoaderRoute: typeof ApiScrubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favicon': {
      id: '/api/favicon'
      path: '/api/favicon'
      fullPath: '/api/favicon'
      preLoaderRoute: typeof ApiFaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compress': {
      id: '/api/compress'
      path: '/api/compress'
      fullPath: '/api/compress'
      preLoaderRoute: typeof ApiCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest/static/$': {
      id: '/ingest/static/$'
      path: '/ingest/static/$'
      fullPath: '/ingest/static/$'
      preLoaderRoute: typeof IngestStaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliRoute: CliRoute,
  CompareRoute: CompareRoute,
  ConvertRoute: ConvertRoute,
  CropRoute: CropRoute,
  FaviconRoute: FaviconRoute,
  FiltersRoute: FiltersRoute,
  GlassRoute: GlassRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  PaletteRoute: PaletteRoute,
  PdfRoute: PdfRoute,
  PrivacyRoute: PrivacyRoute,
  ResizeRoute: ResizeRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ScrubRoute: ScrubRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TracerRoute: TracerRoute,
  WatermarkRoute: WatermarkRoute,
  ApiCompressRoute: ApiCompressRoute,
  ApiFaviconRoute: ApiFaviconRoute,
  ApiScrubRoute: ApiScrubRoute,
  ApiWatermarkRoute: ApiWatermarkRoute,
  IngestSplatRoute: IngestSplatRoute,
  IngestStaticSplatRoute: IngestStaticSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
